CREATE TABLE Pessoas (
PessoaID INTEGER NOT NULL,
Nome VARCHAR (100) NOT NULL DEFAULT'',
Endereco VARCHAR (100) NOT NULL DEFAULT'',
Email VARCHAR (100) NOT NULL DEFAULT'',
Sexo CHAR (1) NOT NULL DEFAULT'',
Telefone INTEGER NOT NULL,
CONSTRAINT PK_Pessoas PRIMARY KEY (PessoaID)
);

CREATE TABLE Historico(
HistoricoID INTEGER NOT NULL,
IdConta INTEGER NOT NULL,
Conta VARCHAR (50) NOT NULL DEFAULT'',
Valor FLOAT NOT NULL,
Data DATE NOT NULL,
Parcelas INTEGER NOT NULL,
CONSTRAINT PK_Historico PRIMARY KEY (HistoricoID)
);

CREATE TABLE MinhaFinancas (
IdConta INTEGER NOT NULL,
PessoaID INTEGER NOT NULL,
HistoricoID INTEGER NOT NULL,
Conta VARCHAR (50) NOT NULL DEFAULT'',
Valor FLOAT NOT NULL,
Data DATE NOT NULL,
Parcelas INTEGER NOT NULL,
CONSTRAINT PK_MinhaFinacas PRIMARY KEY (IdConta),
CONSTRAINT FK_MinhaFinacas_PessoaID FOREIGN KEY (PessoaID) REFERENCES Pessoas (PessoaID),
CONSTRAINT FK_MinhaFinacas_Historico FOREIGN KEY (HistoricoID) REFERENCES Historico (HistoricoID)	
);

